=== gunseful/thirdTask/src/main/resources/gem_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="gem">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="gem" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element ref="name"/>
                            <xs:element ref="preciousness"/>
                            <xs:element ref="origin"/>
                            <xs:element name="visual_parameters" maxOccurs="unbounded" >
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element ref="colour"/>
                                        <xs:element ref="transparency"/>
                                        <xs:element ref="faceting"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="price"/>
                            <xs:element ref="value"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- types-->
    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z][a-z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="preciousness" type="xs:string"/>
    <xs:element name="origin">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="colour">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z][a-z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="price">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="0.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="value">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="transparency">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="faceting">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="4"/>
                <xs:maxInclusive value="15"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== gunseful/thirdTask/src/main/resources/gem.xml
<?xml version="1.0" encoding="UTF-8"?>
<gem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gem_schema.xsd">
    <gem id="id1" >
    <name>Almaz</name>
    <preciousness>precious</preciousness>
    <origin>Africa</origin>
    <visual_parameters>
        <colour>White</colour>
        <transparency>100</transparency>
        <faceting>10</faceting>
    </visual_parameters>
    <price>1.4</price>
    <value>15</value>
    </gem>
    <gem id="id2">
        <name>Rube</name>
        <preciousness>precious</preciousness>
        <origin>USA</origin>
        <visual_parameters>
            <colour>Red</colour>
            <transparency>80</transparency>
            <faceting>5</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>200</value>
    </gem>
    <gem id="id3">
        <name>Sapphire</name>
        <preciousness>precious</preciousness>
        <origin>Kazakhstan</origin>
        <visual_parameters>
            <colour>Green</colour>
            <transparency>65</transparency>
            <faceting>8</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>100</value>
    </gem>
    <gem id="id4">
        <name>Ametrine</name>
        <preciousness>semiprecious</preciousness>
        <origin>Kazakhstan</origin>
        <visual_parameters>
            <colour>Violet</colour>
            <transparency>64</transparency>
            <faceting>7</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>500</value>
    </gem>
    <gem id="id5">
        <name>Amethyst</name>
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visual_parameters>
            <colour>Violet</colour>
            <transparency>75</transparency>
            <faceting>9</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>300</value>
    </gem>
    <gem id="id6">
        <name>Topaz</name>
        <preciousness>semiprecious</preciousness>
        <origin>France</origin>
        <visual_parameters>
            <colour>Blue</colour>
            <transparency>80</transparency>
            <faceting>10</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>115</value>
    </gem>
    <gem id="id7">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Italy</origin>
        <visual_parameters>
            <colour>Blue</colour>
            <transparency>100</transparency>
            <faceting>14</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>30</value>
    </gem>
    <gem id="id8">
        <name>Diamond</name>
        <preciousness>precious</preciousness>
        <origin>Italy</origin>
        <visual_parameters>
            <colour>Blue</colour>
            <transparency>100</transparency>
            <faceting>15</faceting>
        </visual_parameters>
        <price>1.4</price>
        <value>30</value>
    </gem>
</gem>
